# AI VIET NAM – COURSE 2024
# Numpy - Exercise
### Ngày 7 tháng 7 năm 2024

Giới thiệu về bài tập: Ở phần bài tập này các bạn sẽ được ôn tập cách sử dụng thư viện numpy
để thao tác trên 1D và 2D array. Dựa vào đó để giải quyết các bài toán về xử lý ảnh như chuyển ảnh
màu thành ảnh xám và phân tích dữ liệu dạng bảng.

In [1]:
import numpy as np

## Câu hỏi 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9

a) import numpy as np

arr = np. arange (0, 10, 1)

b) import numpy as np

arr = np. arange (1, 10, 1)

c) import numpy as np

arr = np. arange (0, 9, 1)

d) import numpy as np

arr = np. arange (1, 11, 1)

In [5]:
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Câu hỏi 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True

a) arr = np. ones ((3 ,3) ) > 0

b) arr = np. ones ((3 ,3) , dtype = bool )

c) arr = np. full ((3 ,3) , fill_value =True , dtype = bool )

d) a,b and c

In [7]:
#a)
arr = np. ones ((3 ,3) ) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
# b) 
arr = np. ones ((3 ,3) , dtype = bool )
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
#c) 
arr = np. full ((3 ,3) , fill_value =True , dtype = bool )
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Answer d)

## Câu hỏi 3: Kết quả của đoạn code sau đây:

import numpy as np
arr = np. arange (0 ,10)
print (arr [arr %2 == 1])

a) [1 3 5 7 9]

b) [1 2 3 4 5]

c) [2 4 6 8 9]

d) [1 7 5 7 9]

answer: a) [1 3 5 7 9]

## Câu hỏi 4: Kết quả của đoạn code sau đây:
import numpy as np
arr = np. arange (0 ,10)
arr [arr %2 ==1] = -1
print (arr )

a) [ -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]

b) [ 0 -1 2 -1 4 -1 6 -1 8 -1]

c) [ -1 0 -1 -0 -1 0 -1 0 -1 0]

d) [ -1 1 -1 1 -1 1 -1 1 -1 1]

Answer: b) [ 0 -1 2 -1 4 -1 6 -1 8 -1]

## Câu hỏi 5: Kết quả của đoạn code sau đây:
import numpy as np

arr = np. arange (10)

arr_2d = arr. reshape (2 , -1)

print ( arr_2d )

a) [[0 1 2 3 4 5 6 7 8 9]]

b) [[0 1 2 3 4]

    [5 6 7 8 9]]
c) [[0 1 2 3 4]]

d) [[0 1 2 3]

[5 6 7 8]]

In [11]:
arr = np. arange (10)

arr_2d = arr. reshape (2 , -1)

print ( arr_2d )

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Câu hỏi 6: Kết quả của đoạn code sau đây:
1 import numpy as np

2 arr1 = np. arange (10) . reshape (2 , -1)

3 arr2 = np. repeat (1 ,10). reshape (2 , -1)

4 c = np. concatenate ([ arr1 , arr2 ], axis =0)

5 print (" Result : \n", c)

a) [[0 1 2 3 4]

[5 6 7 8 9]

[1 1 1 1 1]

[1 1 1 1 1]]

b) [[0 1 2 3 4]

[5 6 7 8 9]]

c) [[0 1 2 3 4]

[5 6 7 8 9]

[1 1 1 1 1]

[5 6 7 8 9]]

d) [[0 1 2 3 4]]

answer: a)

In [12]:
arr1 = np. arange (10) . reshape (2 , -1)

arr2 = np. repeat (1 ,10). reshape (2 , -1)

c = np. concatenate ([ arr1 , arr2 ], axis =0)

print (" Result : \n", c)

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
